### ISSUE TITLE
NameError: uninitialized constant FrontEndBuilds

### ISSUE THREAD

**Issue by hhff** [tedconf/front_end_builds#55]
Just updated from 0.2.3 -> 0.2.4, and I'm getting this for any command I attempt to run:

```ruby
rake aborted!
NameError: uninitialized constant FrontEndBuilds
/Users/hhff/.rvm/gems/ruby-2.0.0-p576/bundler/gems/front_end_builds-63a9c3362c7f/lib/front_end_builds/middleware/admin_assets.rb:5:in `<top (required)>'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576/bundler/gems/front_end_builds-63a9c3362c7f/lib/front_end_builds/engine.rb:1:in `require'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576/bundler/gems/front_end_builds-63a9c3362c7f/lib/front_end_builds/engine.rb:1:in `<top (required)>'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576/bundler/gems/front_end_builds-63a9c3362c7f/lib/front_end_builds.rb:1:in `require'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576/bundler/gems/front_end_builds-63a9c3362c7f/lib/front_end_builds.rb:1:in `<top (required)>'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:76:in `require'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:72:in `each'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:72:in `block in require'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:61:in `each'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler/runtime.rb:61:in `require'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576@global/gems/bundler-1.7.3/lib/bundler.rb:133:in `require'
/Users/hhff/dev/SC/face_files/backend/config/application.rb:7:in `<top (required)>'
/Users/hhff/dev/SC/face_files/backend/Rakefile:4:in `require'
/Users/hhff/dev/SC/face_files/backend/Rakefile:4:in `<top (required)>'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `eval'
/Users/hhff/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

Don't have time to troubleshoot - rolling back to 0.2.3 for now, thought I'd let you guys know

hx

**Comment by ryanto** [comment]
Thanks.

What commands are you trying to run?

**Comment by ryanto** [comment]
Ah thanks, didn't see your PR. Nice catch. I'll publish a new version soon.

**Comment by hhff** [comment]
No probs @ryanto !
